// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace TransitAPI.Models
{
    public partial class Entity
    {
        public string AgencyId { get; set; }
        public string VehicleId { get; set; }
        public string VehicleLabel { get; set; }
        public long Timestamp { get; set; }
        public string RouteId { get; set; }
        public long DirectionId { get; set; }
        public string TripId { get; set; }
        public int? Bearing { get; set; }
        public bool BearingValid { get; set; }
        public string RouteColor { get; set; }
        public string RouteTextColor { get; set; }
        public string RouteShortName { get; set; }
        public string RouteLongName { get; set; }
        [Column(TypeName = "decimal(18,10)")]
        public decimal? Latitude { get; set; }
        [Column(TypeName = "decimal(18,10)")]
        public decimal? Longitude { get; set; }
    }
}
