// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TransitWorker.Models;

public partial class Entity
{
    public Guid Id { get; set; }

    public string AgencyId { get; set; }

    public string VehicleId { get; set; }

    public string VehicleLabel { get; set; }

    public long Timestamp { get; set; }

    public string RouteId { get; set; }

    public long DirectionId { get; set; }

    public string TripId { get; set; }

    public double Bearing { get; set; }

    public bool BearingValid { get; set; }

    public double Latitude { get; set; }

    public double Longitude { get; set; }

    public DateTime Created { get; set; }

    public bool Deleted { get; set; }
}