// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TransitWorker.Models;

public partial class Route
{
    public Guid Id { get; set; }

    public string RouteId { get; set; }

    public string AgencyId { get; set; }

    public string RouteShortName { get; set; }

    public string RouteLongName { get; set; }

    public string RouteDesc { get; set; }

    public string RouteType { get; set; }

    public string RouteUrl { get; set; }

    public string RouteColor { get; set; }

    public string RouteTextColor { get; set; }

    public int? RouteSortOrder { get; set; }

    public int? ContinuousPickup { get; set; }

    public int? ContinuousDropOff { get; set; }
}